CREATE OR REPLACE PACKAGE "RIS_SERVER_PACKAGE" IS

  FUNCTION "GET_NEW_RIS_ID"
  RETURN VARCHAR2;

  FUNCTION "GET_NEW_STUDYINSTANCEUID" (
  "P_RIS_ID" IN VARCHAR2)
  RETURN VARCHAR2;

  FUNCTION STRTOKEN(
    "P_STRING" VARCHAR2, 
    "P_DELIMIT" VARCHAR2,
    "P_POS" POSITIVEN := 1,
    "P_NTH" POSITIVEN := 1,
    "P_EOD" VARCHAR2 := NULL)
  RETURN VARCHAR2;

  FUNCTION YEARS_OF_AGE(
    "P_BIRTHDAY" IN DATE,
    "P_BASEDATE" IN DATE := SYSDATE,
    "P_METHOD" IN NUMBER := 0 )
  RETURN NUMBER;

  FUNCTION TO_NUMBER_DEF(
    P_VALUE      IN VARCHAR2,
    P_PRECISION    IN NUMBER,
    P_SCALE     IN NUMBER,
    P_DEFAULT   IN NUMBER := NULL
  )
  RETURN NUMBER;

  --éwíËÇ≥ÇÍÇΩïbêîÇí«â¡ÇµÇƒï‘Ç∑
  --P_DATE      IN DATE ì˙ït
  --P_SECOND    IN NUMBER í«â¡Ç∑ÇÈïbêî
  FUNCTION ADD_SECONDS(
    P_DATE      IN DATE,
    P_SECOND    IN NUMBER
  )
  RETURN DATE;

END "RIS_SERVER_PACKAGE";
/
